db-uri = "postgres://authenticator:local-only@127.0.0.1:54322/postgres"
db-schemas = "public"
db-anon-role = "anon"
jwt-secret = "local-test-secret-not-for-production-0123456789"
server-host = "127.0.0.1"
server-port = 3000
